spring:
  application:
    name: cwa-verification-portal

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

keycloak:
  auth-server-url: https://auth-testing.exo.grnet.gr/auth
  principal-attribute: preferred_username
  public-client: true
  realm: cwa
  resource: verification-portal

keycloak-pw:
  reset-url: https://auth-testing.exo.grnet.gr/auth/realms/cwa/account/password

server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  error:
    whitelabel:
      enabled: false
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 14400s

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  health:
    probes:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

cwa-verification-server:
  url: https://v-server-testing.exo.grnet.gr
  ssl:
    enabled: false
    one-way: false
    two-way: false
    hostname-verify: false
    key-store: classpath:keystore.jks
    key-store-password: iti2020!#
    trust-store: classpath:truststore.jks
    trust-store-password: iti2020!#
    
rateLimiting:
  enabled: true
  seconds: 30

host-header:
  whitelist: localhost:8081,exo.grnet.gr,portal-testing.exo.grnet.gr

pod:
  ip: 127.0.0.1
  port: 8081
